language: C
os: osx
git:
    submodules: true
before_install:
    - test -n $CC && unset CC
install:
    - pushd framework && make && popd
script:
    - make -C libft-tests all
    - make -C libft-tests test
after_success: true
after_failure: true








